### ISSUE TITLE
DECK App status indicator does not work

### ISSUE THREAD

**Issue by solidterre** [deck-app/laravel#10]
Computer: Apple MacBook Pro 14" - Apple M1 Pro (Sillicon) - MacOS 13.2.1 (22D68)

Something which has been confusing me for some time now: the container status indicator does not seem to work for me.

As you will see in the screenshots, it seems Deck App does not register that the container has successfully launched and is running. Which leaves the user struggling to know if the container actually is or isn't running or whether there is or isn't an issue ongoing.

![Capture d’écran 2023-04-06 à 10 59 40](https://user-images.githubusercontent.com/8171049/230328359-122792ef-199a-4a9b-918c-511af5e25c6c.png)
![Capture d’écran 2023-04-06 à 11 00 06](https://user-images.githubusercontent.com/8171049/230328353-cbb40dc6-1e46-479a-9303-05a6232de19e.png)

**Comment by ndas198** [comment]
Hi @rakami-solid, Thank you so much for sharing your feedback, we will prioritise testing as soon as we can and try see if we can replicate this.
and Can you reload the "DECK-APP", we'd be happy to help.

**Comment by solidterre** [comment]
Created issue in wrong GITHUB repo. Opened https://github.com/sfx101/deck/issues/136
