### ISSUE TITLE
Laravel image seems to be missing NPM for building assets

### ISSUE THREAD

**Issue by solidterre** [deck-app/laravel#11]
I use Deck App as a dev env. tool but this stack seems to be missing NPM. Is it possible to add it by default ?

**Comment by nabad600** [comment]
Hi @rakami-solid, Thank you for your feedback, we are checked and found that npm already integrated, please find the below mention snapshot.

![image](https://github.com/deck-app/laravel/assets/67466982/6f63dae7-aaf0-4d5c-974e-1a7b83918962)
Please let me know if any issues please share the log/snapshot. We'd be happy to help.
