### ISSUE TITLE
ERROR Load meta data

### ISSUE THREAD

**Issue by jdirciog** [deck-app/laravel#12]
![imagen](https://github.com/deck-app/laravel/assets/39680923/94363d22-f4dc-4e15-81eb-d97d6f88339b)

**Comment by nabad600** [comment]
Hi @jdirciog, Thank you for using DECK, We are investigating and haven't found any issue, 
please check out your network, I think it's some block, [Laravel](https://github.com/deck-app/laravel/actions/runs/7688556575) 
we are happy to help you.

**Comment by luchtech** [comment]
Yeah, seems like a network issue on your end. Please send an update if this is already fixed, @jdirciog .
