### ISSUE TITLE
network deck-app not found

### ISSUE THREAD

**Issue by nilo0522** [deck-app/laravel#17]
<img width="593" alt="Screenshot 2024-07-04 at 9 54 52 AM" src="https://github.com/deck-app/laravel/assets/52353875/7183877a-21f0-41a5-813f-fd4378e4810a">

**Comment by sfx101** [comment]
As a temporary fix, please run this command in the terminal

```
docker network create -d bridge deck-app
``` 

We will look further into this on why the network was not created by default/
