### ISSUE TITLE
Laravel 9.0 - PHP 8.1

### ISSUE THREAD

**Issue by alexevladgabriel** [deck-app/laravel#2]
Posibility to use latest release of Laravel and PHP.

**Comment by alexevladgabriel** [comment]
Would be a good idea to have a option for latest version always. It would be more easy for people when choosing.

**Comment by sfx101** [comment]
Absolutely! We're working on it, will keep you posted on this issue

**Comment by nabad600** [comment]
Hi @alexevladgabriel  , merged a PR to add the stack to the marketplace. Please restart the app & try. Let us know for any issues, we'd be happy to help
