### ISSUE TITLE
Unable to create a project

### ISSUE THREAD

**Issue by duboiss** [deck-app/laravel#4]
On every technology I have an "Invalid github link." message when I click on the top-right button "Install".
![CleanShot 2022-05-11 at 15 36 02@2x](https://user-images.githubusercontent.com/29716703/167862838-4482c5e5-110c-4e92-9ee0-168de54dc382.png)
Its the first time I install deck.

I use the MacOS app at the latest version.

**Comment by nabad600** [comment]
Hi, @duboiss, please restart the app & try. Let us know for any issues, we'd be happy to help

![image](https://user-images.githubusercontent.com/67466982/172141160-6337f87c-1037-4eba-8c36-43f465cd8c9a.png)

**Comment by duboiss** [comment]
Seems fixed, thanks.
