### ISSUE TITLE
Invalid github link (installation problem)

### ISSUE THREAD

**Issue by ghost** [deck-app/laravel#5]
Hello!
Installed the latest version for Windows
When trying to start work - nothing happens ...
Also constantly flashes the bell to the bottom left ...
WSL2 is installed and launched
Can I give any information to solve this problem?

Windows 10 Pro (last update), WSL2
![image](https://user-images.githubusercontent.com/108523578/177257741-ec075b7a-24f3-4bf2-9152-da36f2e5ed95.png)

**Comment by ghost** [comment]
after 5 restarts - working... =)
delete issue, pls

**Comment by sfx101** [comment]
Awesome.
