### ISSUE TITLE
Invalid github link 

### ISSUE THREAD

**Issue by riftwebdev** [deck-app/laravel#7]
Having this issue, already restarted both pc and the app multiple times.

![image](https://user-images.githubusercontent.com/58982469/180513648-2f425cd6-330c-4ce2-a741-4d67239534d0.png)

**Comment by nabad600** [comment]
Hi @riftwebdev, thanks for reporting, but don't found any kind of issue, please make sure internet connection is active in your system.
Please close DECK app in taskmenu and do the following process.
1. **If using Windows,**
   Delete **.deck** folder under **C:/User/!User Name!/.deck**
2. **If Using Linux**
   Delete **.deck** folder under **/home/!User Name!/.deck**
3. **If Using MAC**
   Delete **.deck** folder under **/Users/!User Name!/.deck**
   
 After Delete folder start DECK app.
![image](https://user-images.githubusercontent.com/67466982/180724786-2d312a46-2eec-4fce-8b87-ec5485e1a113.png)

 Let us know of any issues, we'd be happy to help.

**Comment by riftwebdev** [comment]
This fixed it, thanks.
