### ISSUE TITLE
Error on Installing laravel - Windows 11

### ISSUE THREAD

**Issue by anburocky3** [deck-app/laravel#8]
```bash
error during connect: Get "http://127.0.0.1:2376/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22com.docker.compose.container-number%3D1%22%3Atrue%2C%22com.docker.compose.project%3Dcheck-laravel%22%3Atrue%2C%22com.docker.compose.service%3Dlaravel%22%3Atrue%7D%7D&limit=0": dial tcp 127.0.0.1:2376: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by nabad600** [comment]
Hi @anburocky3 , thanks for reporting.

Could you please do the following?

 1. If you use "Docker Desktop", open the deck app and go to setting, click on Docker engine & uncheck Remote engine
 
![image](https://user-images.githubusercontent.com/67466982/191013577-61b410b2-eca1-4b1a-9d34-5dbde7b3defc.png)

also remove "DOCKER_HOST" from environment variables
![image](https://user-images.githubusercontent.com/67466982/191014433-ecdbbd39-e0e7-43a2-ba84-75639cb74741.png)


2. If you use `wsl with virtual host`, then do the following?
    a. Uninstall `docker decktop` and deleted `` c:/users/<user name>/.deck``
    b. open the deck app and go to setting, click on Docker engine & uncheck Remote engine
    ![image](https://user-images.githubusercontent.com/67466982/191013577-61b410b2-eca1-4b1a-9d34-5dbde7b3defc.png)
    
    reopen `deck` app and installation page should appear. Below is the screenshot for your reference
    ![image](https://user-images.githubusercontent.com/67466982/191015275-138a9950-674e-44e5-b758-a7ab8a8d91e2.png)
    
     Please verify `deck-app` virtual host created or not
     ![image](https://user-images.githubusercontent.com/67466982/191015513-3ef94dea-fb6e-4525-ae93-45b7f1d3d3c1.png)

Appreciate your feedback here.

**Comment by anburocky3** [comment]
I have not installed docker. I thought, the deck would install that automatically for me? Do i need to install docker in my system?

**Comment by nabad600** [comment]
Hi @anburocky3, thanks for reporting.

The Deck not install Docker desktop automatically. Please go through option 2
or 
Could you please run this command and paste the output?

`wsl -l -v`

Also, please try restarting the DECK app and see if the problem persists.

**Comment by anburocky3** [comment]
i receive the following response:
```bash
$ wsl -l -v
The parameter is incorrect.
```

**Comment by nabad600** [comment]
Hi, @anburocky3, Thanks for reporting,
Step 1: Uninstall `DECK` app.
Step 2. Enable Virtual Machine Platform and Windows Subsystem for Linux and restart windows
![image](https://user-images.githubusercontent.com/67466982/191052081-8ad8cf0f-7a38-4a94-a47e-1ce054917def.png)
Step 3: Install `DECK` app and It's working fine

Appreciate your feedback here.
