### ISSUE TITLE
i can't create project

### ISSUE THREAD

**Issue by Abdullahiyahye** [deck-app/laravel#9]
this the problem
 => ERROR [13/36] RUN if [ -z "php8-pdo_mysql php8-pdo_pgsql php8-sqlite3 php8-pgsql php8-pecl-redis" ] ; then e  15.2s
 > [13/36] RUN if [ -z "php8-pdo_mysql php8-pdo_pgsql php8-sqlite3 php8-pgsql php8-pecl-redis" ] ; then echo "No additional PHP extensions added" ;else apk add --no-cache php8-pdo_mysql php8-pdo_pgsql php8-sqlite3 php8-pgsql php8-pecl-redis ;fi:

**Comment by nabad600** [comment]
Hi @Abdullahiyahye,
Thank you for your valuable feedback, the issue exists in PHP versions 8.1 & 8.2, and we are working on the fix.

**Comment by Abdullahiyahye** [comment]
thank you @nabad600

**Comment by nabad600** [comment]
Hi @Abdullahiyahye, 
We've fixed the issue. We'd be happy to help.
